### PR TITLE
Fix blank lines

### LINKED ISSUE #1: Falha ao processar linhas em branco
Exemplo, caso o arquivo `input.txt` esteja com uma última linha em branco, quebra o processamento.

Bug encontrado pela @FaveroNath
image

### PR DESCRIPTION
**Pull request by sernajoto**
Refente a Issue #1 Falha ao processar linhas em branco

closes #1

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -27,11 +27,11 @@ async function createOwaspSuppressions() {
   for (const line of lines) {
     const res = reg.exec(line);
 
+    if (!res?.[0] || line === "") continue; // ignore the line
```
Comment (ceopaludetto) [inline src/index.ts]: Add a trim to avoid lines with empty spaces too

```suggestion
    if (!res?.[0] || line.trim() === "") continue; // ignore the line
```

**Review by ceopaludetto — CHANGES_REQUESTED** [review]

**Review by ceopaludetto — APPROVED** [review]
LGTM!
